name: hello_world
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.1.12
  fluttertoast: ^8.2.4
  qr_code_scanner: ^1.0.1
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3
  lottie: ^2.7.0
  firebase_core: ^2.21.0
  firebase_analytics: ^10.7.2
  connectivity_plus: ^5.0.2
  flutter_lints: ^3.0.1
  rflutter_alert: ^2.0.7
  http: ^1.1.2
  url_launcher: ^6.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ptm.png"
  

flutter:
  assets:
    - assets/images/
    - assets/animation/
    - assets/animation/ppmana.json
    - assets/json/

  fonts: 
    - family: Cario
      fonts:
        - asset: assets/font/Cairo-Regular.ttf

  uses-material-design: true
